"""Static UI contract checks for SweepyMod's non-browser dashboard shell.

The app relocates some nodes at runtime and creates other nodes from templates,
so this test intentionally checks required static IDs while allowlisting dynamic
IDs that are generated by app.js itself.
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
APP_JS = (ROOT / "public" / "app.js").read_text(encoding="utf-8", errors="replace")
INDEX = (ROOT / "public" / "index.html").read_text(encoding="utf-8", errors="replace")

DYNAMIC_IDS = {
    # v2.1: persistent BETA badge appended to <body> by applyBetaBadge().
    "beta-build-badge",
    "career-pill",
    # Character Profile panel — these nodes are built via innerHTML inside the
    # active-profile renderer, not present statically in index.html.
    "cp-autopick-cb",
    "cp-autopick-save",
    "cp-epithets-clear",
    "cp-epithets-save",
    "cp-refresh",
    "guest-parent-grid",
    "guest-parent-refresh-btn",
    "guest-parent-status",
    "guest-parents-section",
    "preset-add-btn",
    "preset-del-btn",
    "preset-edit-skills-btn",
    "preset-save-btn",
    "preset-section",
    "preset-select",
    "preset-skill-threshold",
    "save-races-btn",
    "settings-reset-trackblazer",
    "skill-add-tier-btn",
    "skill-blacklist-all-btn",
    "skill-blacklist-container",
    "skill-clear-blacklist-btn",
    "skill-config-list",
    "skill-config-search",
    "skill-config-summary",
    "skill-deselect-all-btn",
    "skill-filters",
    "skill-list",
    # Built into the skill-settings section via a template string in renderSkillConfig.
    "skill-optimizer-toggle",
    "skill-plan-body",
    "skill-search",
    "skill-select-all-btn",
    "skill-tiers-container",
    "sweepy-theme-select",
    "tp-recovery-mode-select",
    "tp-recovery-potion-count",
    "tp-recovery-status",
    "v4-analytics",
    "v4-fan-bonus",
    "v4-health",
    "v4-include-op",
    "v4-max-streak",
    "v4-snapshot-timeline",
    "v5-decision-trace",
    "v516-library-group",
    "v518-left-stack",
    "v520-setup-shortcut-btn",
    # v2.1: the standalone "AI Learning" launch button was folded into the
    # unified "DIAG / AI" page (v516-diagnostics-btn + [data-diagai-tab] tabs).
    # app.js keeps the cached ref + click binding behind optional chaining so it
    # no-ops when the static button is absent.
    "v535-ai-learning-btn",
    # Help-modal empty-state node, created via createElement in the help panel.
    "v6719-help-empty",
    # Userdata diagnostics fallback card injected into the Diagnostics modal.
    "v71-userdata-diag-card",
    "v71-userdata-diag-open-btn",
    "v71-userdata-diag-warning",
    # v7.3 Manual Skill Tiers section — built via a template string in app.js
    # (renderManualTierSection / search results), not static in index.html.
    "v73-dont-spend-extra",
    "v73-manual-tier-mode-badge",
    "v73-manual-tier-results",
    "v73-manual-tier-rows",
    "v73-manual-tier-search",
    "v73-manual-tier-target",
    "weighted-blacklist",
    "weighted-forced-skills",
    "weighted-live-preview",
    "weighted-manual-weights",
    "weighted-max-green",
    "weighted-profile",
    "weighted-save-btn",
    "weighted-skill-list",
    "weighted-skill-search",
    "weighted-track",
    "weighted-w-community",
    "weighted-w-distance",
    "weighted-w-green",
    "weighted-w-recommended",
    "weighted-w-style",
    "weighted-w-yellow",
}


def html_ids():
    return set(re.findall(r'id=["\']([\w-]+)["\']', INDEX))


def test_static_appjs_ids_exist_in_index_html():
    needed = set(re.findall(r"getElementById\(['\"]([\w-]+)['\"]\)", APP_JS)) - DYNAMIC_IDS
    missing = needed - html_ids()
    assert not missing, f"index.html is missing static ids app.js needs: {sorted(missing)}"


def test_static_class_selectors_exist():
    for cls in ("navbar", "split-gutter-controls", "title"):
        assert f'class="{cls}' in INDEX or f' {cls}' in INDEX, f"missing static class: {cls}"
    # v2.1: the navbar title brand was changed from a text <span> to the Icarus
    # logo <img>. The contract is that .title still carries its brand content.
    title = re.search(r'class="title"[^>]*>(.*?)</h1>', INDEX, re.S)
    assert title, ".title (navbar brand) element must exist"
    assert "<span" in title.group(1) or "<img" in title.group(1), (
        ".title must contain its brand content (a <span> or the logo <img>)"
    )


def test_collapse_buttons_present():
    for el_id in ("setup-collapse-btn", "content-collapse-btn"):
        assert f'id="{el_id}"' in INDEX, f"missing {el_id}"


def test_modular_assets_are_referenced_and_exist():
    assets = {
        "css/shell.css": ROOT / "public" / "css" / "shell.css",
        "js/monitor.js": ROOT / "public" / "js" / "monitor.js",
        "js/parent-filter.js": ROOT / "public" / "js" / "parent-filter.js",
        "app.js": ROOT / "public" / "app.js",
        "styles.css": ROOT / "public" / "styles.css",
    }
    for ref, path in assets.items():
        assert ref in INDEX, f"index.html does not reference {ref}"
        assert path.exists(), f"missing asset file: {path}"
